### ISSUE TITLE
CDK Autocompletion for Projects in Python

### ISSUE THREAD

**Issue by asifiqbal** [towardsthecloud/vscode-cdk-snippets#1]
**Is your feature request related to a problem? Please describe.**
I like to see autocompletion support projects in pythons

**Describe the solution you'd like**
Python support would be awesome

**Describe alternatives you've considered**
I have not found one that autocompletes CDK codes written in python

**Additional context**
Thanks for your page https://dannys.cloud/ showing all kinds of cool tips/tricks to make code development easier for cloudformation newbies

**Comment by dannysteenman** [comment]
Hi @asifiqbal I've managed to add support for L1 constructs snippets in AWS CDK Python! Update the [extension](https://marketplace.visualstudio.com/items?itemName=dannysteenman.cdk-snippets), then open up a CDK Python project and type `l1` to trigger the L1 construct autocomplete.
